#include "utils.h"

//#define BUFFER_SIZE 128
//tatic unsigned char buffer[BUFFER_SIZE];

//Compile with: gcc checkSYS.c -lm -lssl -lcrypto -o checkSYS.lxf
//openssl dgst * | grep -ohs " \b[0-9a-z].*" Per prendere gli hash e metterli in un file
//Prima va lanciato genSHA1.c compilandolo opportunamente per le cose di cui si vuole generare gli hash quindi ad esempio 
//Per un server rimuovere il commento per il percorso /opt/lammp il file di cui parlo è genSHA1.c
//Una volta che il file listsum viene riempito dei valori hash prendere l'hash di listsum e usarlo per lanciare checkSYS.lxf
/*
int getline(char s[], int lim){
	int c, i;
	for(i=0;i<lim-1 && (c=getchar())!=EOF && c!='\n';++i)
		s[i]=c;
	if(c=='\n'){
		s[i]=c;
		++i;
	}
	s[i]='\0';
	return i;
}*/


int is_a_file(const char *pth){
	struct stat path_stat;
	stat(pth,&path_stat);
	return S_ISREG(path_stat.st_mode);
}

void recursiveGenSHA1(char *name, int level, FILE* pf){
	DIR *dir;
	struct dirent *entry;
	char* linea;
	char path[1024];
	if(is_a_file(name)){
		linea="";
		linea=generaSHA1(name);
		fputs(name,pf);
		fputs(",",pf);
		fputs(linea,pf);
		fputs("\n",pf);
	}	
	if(!(dir = opendir(name))){
		return;
	}
	if(!(entry = readdir(dir))){
		return;
	}
	do{
		path[0]='\0';
		int len = snprintf(path, sizeof(path) - 1, "%s/%s", name, entry->d_name);
		path[len] = 0;
		if(strcmp(entry->d_name, ".") == 0 || strcmp(entry->d_name, "..") == 0){continue;}
		linea="";
		linea=generaSHA1(path);
		fputs(path,pf);
		fputs(",",pf);
		fputs(linea,pf);
		fputs("\n",pf);
		recursiveGenSHA1(path, level + 1,pf);
	}while((entry = readdir(dir)));
	closedir(dir);
}

int main(int argc, char *argv[]){
    if(argc<4){
		printf("\n First argument is the SHA1 of listsum obtained from genSHA1.lxf\n");
		printf("\n Second argument is the path to listsum (check reading permission)\n");
		printf("\n Third argument is the path to checklist (a file generated by this program)\n");
		printf("\n Fourth argument is the path to the text file within the paths of files to verify /home/user/mypaths.csv\n");
		printf("\n NOTE: You do not need checklist to exist just give a path with writing permission\n");
		printf("\n NOTE: Every line of the file must be a path to a file or a folder\n");
		return 0;	
    }else{
		const char* shatc = argv[1];
		const char* listsum = argv[2];
		const char* checklist = argv[3];
		const char* mypaths = argv[4];
		char* dir=(char*)malloc(380*sizeof(char));	
		memset(dir,0,sizeof(char));
		char* sha=generaSHA1(listsum);
		char* crc;
		char c;
		int i, j;
    		FILE* pf;
    		FILE* cf;
		FILE* csv;
		if(strcmp(sha,shatc)==0){
			printf("\nReady to check the system!\n\nChecking...\n");
			pf=fopen(checklist,"wb");
			cf=fopen(listsum,"rb");
			csv=fopen(mypaths,"r");
			c=fgetc(csv);
			i=0;
			while(!feof(csv) && c!=0xff){
				while(c!='\n' && c!='\r' && c!=EOF){
				dir[i]=(char)c;
					i+=1;
					dir[i]='\0';
					c=fgetc(csv);	
				}
				i=0;
				c=fgetc(csv);
				recursiveGenSHA1(dir,3,pf);	
			}
			fclose(csv);
			fclose(pf);
			fclose(cf);
			crc=generaSHA1("checklist");
			if(strcmp(sha,crc)!=0){
				printf("\nCorruption detected!\n");
				pf=fopen("/home/tc/inculato.txt","w");
				cf=fopen(listsum,"rb");
				csv=fopen(checklist,"rb");
				fputs("Read datetime file creation: \n\r",pf);
				fputs("If a file is erased the list below is unuseful, the same is if renamed \n\r",pf);	
				char* dir2=(char*)malloc(380*sizeof(char));	
				char c2=fgetc(csv);
				c=fgetc(cf);
				i=0;
				j=0;
				memset(dir2,0,sizeof(char));
				while(!feof(cf) && c!=0xff){
					while(c!='\n' && c!='\r' && c!=EOF){
						dir[i]=(char)c;
						dir2[i]=(char)c2;
						i+=1;
						j+=1;
						dir[i]='\0';
						dir2[i]='\0';	
						c2=fgetc(csv);	
						c=fgetc(cf);	
					}
					i=0;
					j=0;
					c=fgetc(cf);
					c2=fgetc(csv);
					if(strcmp(dir,dir2)!=0){
						fputs("Original: ",pf);
						fputs(dir,pf);
						fputs("\n\r",pf);
						fputs("Detected: ",pf);
						fputs(dir2,pf);
						fputs("\n\r",pf);
					}		
				}
				fflush(stdin);
				fclose(pf);	
				fclose(cf);
				fclose(csv);
				
			}else{
				printf("\nEverything is OK!\n");	
			}
		}else{
		printf("\nWarning: listsum has been modified!\n");
		}
	}
}
